#!/bin/bash
myip=`curl http://169.254.169.254/latest/meta-data/local-ipv4`
Owner="Snyatkov_V"
Project="Demo"

sed "s/\${Myip}/$myip/; s/\${Owner}/$Owner/; s/\${Project}/$Project/" /var/www/tmp/index.html > /var/www/html/index.html
